function Pos = funcFwKine(in1,in2)
%FUNCFWKINE
%    POS = FUNCFWKINE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Oct-2020 10:24:43

Ang1 = in1(1,:);
Ang2 = in1(2,:);
Ang3 = in1(3,:);
Len1 = in2(1,:);
Len2 = in2(2,:);
t2 = cos(Ang2);
t3 = Len1.*t2;
t4 = Ang2+Ang3;
t5 = cos(t4);
t6 = Len2.*t5;
t7 = t3+t6;
Pos = [t7.*cos(Ang1);t7.*sin(Ang1);Len1.*sin(Ang2)+Len2.*sin(t4)];
