function mat = funcdPosMatrix(in1,in2)
%FUNCDPOSMATRIX
%    MAT = FUNCDPOSMATRIX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    21-Dec-2020 16:58:31

Eta1 = in1(1,:);
Eta2 = in1(2,:);
Eta3 = in1(3,:);
Pos1 = in2(1,:);
Pos2 = in2(2,:);
Pos3 = in2(3,:);
t2 = cos(Eta1);
t3 = sin(Eta3);
t4 = cos(Eta3);
t5 = sin(Eta1);
t6 = sin(Eta2);
t7 = cos(Eta2);
t8 = t4.*t5;
t9 = t8-t2.*t3.*t6;
t10 = t2.*t4;
t11 = t3.*t5.*t6;
t12 = t10+t11;
t13 = t2.*t3;
t14 = t13-t4.*t5.*t6;
t15 = t3.*t5;
t16 = t2.*t4.*t6;
t17 = t15+t16;
mat = reshape([Pos3.*t14+Pos2.*t17,-Pos2.*t9-Pos3.*t12,Pos2.*t2.*t7-Pos3.*t5.*t7,-Pos1.*t4.*t6+Pos3.*t2.*t4.*t7+Pos2.*t4.*t5.*t7,-Pos1.*t3.*t6+Pos3.*t2.*t3.*t7+Pos2.*t3.*t5.*t7,-Pos1.*t7-Pos3.*t2.*t6-Pos2.*t5.*t6,Pos3.*t9-Pos2.*t12-Pos1.*t3.*t7,-Pos2.*t14+Pos3.*t17+Pos1.*t4.*t7,0.0],[3,3]);
